# Generated by Django 6.0.6 on 2026-06-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('dono', models.CharField(blank=True, help_text='Quem detém o lock.', max_length=128)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text="Categoria do job, ex.: 'sync_github'.", max_length=64)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('rodando', 'Rodando'), ('concluido', 'Concluído'), ('falhou', 'Falhou')], default='pendente', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Parâmetros do job.')),
                ('resultado', models.JSONField(blank=True, help_text='Saída ou erro do job.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['status', 'tipo'], name='operations__status_fd1242_idx')],
            },
        ),
    ]
